server:
  port: 8000
spring:
  application:
    name: server-weather-city
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keep?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
